services:
  - type: web
    name: movillibre-backend
    runtime: node
    rootDir: evobike-bicivalle/backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
